FROM ubuntu

# ubuntu setup
RUN apt-get update -y
RUN apt-get install net-tools -y
RUN apt-get install iputils-ping -y
RUN apt-get install golang -y
RUN apt-get install curl -y
RUN apt-get install vim -y

COPY node /
